---
- name: Symlink Files
  file:
    src: '{{ item.src }}'
    dest: '{{ ansible_env.HOME }}/{{ item.path }}'
    state: link
    force: true
  with_filetree: '{{ ansible_env.PWD }}/files/'
  when: item.state == 'file'
